### ISSUE TITLE
meta: core: stdcm: use the new conflict detection

### ISSUE THREAD

**Issue by alexandredamiron** [alexandredamiron/osrd-fork#858]
We need to interface the STDCM module with the conflict detection module to find appropriate results.

This ticket only describes the changes that need to be done on the STDCM side of core.

____

Prerequisites: 

- [x] https://github.com/osrd-project/osrd/issues/4003

To do:

- [ ] the location part of an stdcm edge should be changed to a pair of route + block (rather than a simple route)
- [ ] the stdcm algorithm should handle a `NotEnoughLookahead` response from `RouteAvailabilityInterface` (currently unsupported)
- [x] #4771
- [ ] write a new implementation of `RouteAvailabilityInterface`, calling the new conflict detection modules
- [ ] `RouteAvailabilityLegacyAdapter` should be moved to a test module and renamed accordingly
